import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { API_URL } from "@/configs/constant";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchData() {
  const res = await fetch(API_URL + "/common/config");
  const data = await res.json();
  return data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchData();
  return (
    <html lang="en">
      <body>
        <div className="font-sans">
          <Header />
          {children}
          <Footer footer_content={data.footer} />
        </div>
      </body>
    </html>
  );
}
